import Head from 'next/head'
import { SeilaStyle } from '../styles/styled.js'

export default function Home() {
  return (
      <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SeilaStyle>
        AAAAAAAAAAAA <button>BBBBBB</button>
      </SeilaStyle>
      </>
  )
}
