

module.exports = {
  env: {
    IMGUR_CLIENT_ID: process.env.NEXT_PUBLIC_IMGUR_CLIENT_ID,
    FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL,
    BACKEND_SOCKET_URL: process.env.NEXT_PUBLIC_BACKEND_SOCKET_URL,
    BACKEND_SOCKET_URL_LOCAL: process.env.NEXT_PUBLIC_BACKEND_SOCKET_URL_LOCAL,
    BACKEND_URL_LOCAL: process.env.NEXT_PUBLIC_BACKEND_URL_LOCAL,
    GOOGLE_MAPS_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
  }
}

